import express from 'express'; import cors from 'cors'; import { createServer } from 'node:http'; import { Server } from 'socket.io';
import type { Alert, Bus, EventType, Snapshot, UrbanEvent } from '@cityfleet/shared';
import { makeBuses, roads, routes, seededEvents } from './data.js'; import { DemoDetectionProvider, IntelligenceEngine, pointAt } from './engine.js';

const app=express(); app.use(cors()); app.use(express.json()); const http=createServer(app); const io=new Server(http,{cors:{origin:'*'}});
let buses:Bus[]=makeBuses(), events:UrbanEvent[]=seededEvents(), alerts:Alert[]=events.map(e=>({id:`ALT-${e.id}`,eventId:e.id,priority:e.priority,status:'open',createdAt:e.detectedAt}));
const engine=new IntelligenceEngine(events,roads,alerts); const provider=new DemoDetectionProvider(); const simulation={running:true,speed:1,tick:0};
const snapshot=():Snapshot=>({buses,routes,events,roads,alerts,simulation}); const publish=(kind:string,payload:unknown)=>{io.emit(kind,payload);io.emit('snapshot',snapshot())};
function emitScenario(type:EventType, busId:string, confidence:number, roadId:string) { const bus=buses.find(b=>b.id===busId)!; const road=roads.find(r=>r.id===roadId)!; const point=road.geometry[Math.floor(road.geometry.length/2)]; bus.latitude=point.lat;bus.longitude=point.lng; const event=engine.ingest(bus,provider.detect(type,confidence),roadId); publish('event:upsert',event); return event; }
app.get('/api/health',(_q,res)=>res.json({status:'ok',provider:provider.name,model:'demo deterministic adapter'}));
app.get('/api/snapshot',(_q,res)=>res.json(snapshot())); app.get('/api/events',(_q,res)=>res.json(events)); app.get('/api/buses',(_q,res)=>res.json(buses));
app.post('/api/simulation/:command',(req,res)=>{const command=req.params.command;if(command==='start')simulation.running=true;if(command==='pause')simulation.running=false;if(command==='reset'){buses=makeBuses();simulation.tick=0;}if(command==='speed')simulation.speed=Math.max(.25,Math.min(8,Number(req.body.speed)||1));publish('simulation:update',simulation);res.json(simulation)});
app.post('/api/demo/:scenario',(req,res)=>{const s=req.params.scenario; let created:UrbanEvent[]=[]; if(s==='pothole') created=[emitScenario('pothole','BUS-004',.86,'road-mg')]; else if(s==='confirmation'){created=[emitScenario('pothole','BUS-004',.86,'road-mg'),emitScenario('pothole','BUS-007',.91,'road-mg'),emitScenario('pothole','BUS-009',.94,'road-mg')];} else if(s==='congestion'){created=['BUS-001','BUS-002','BUS-005','BUS-008'].map((id,i)=>emitScenario('congestion',id,.78+i*.03,'road-old-airport'));} else if(s==='sign')created=[emitScenario('damaged_sign','BUS-004',.82,'road-mysore')]; else if(s==='water')created=[emitScenario('waterlogging','BUS-003',.9,'road-outer-ring')]; else return res.status(404).json({error:'Unknown scenario'}); res.json({created});});
app.post('/api/events/:id/:action',(req,res)=>{const e=events.find(x=>x.id===req.params.id);if(!e)return res.status(404).end(); if(req.params.action==='acknowledge')e.status='acknowledged';if(req.params.action==='resolve')e.status='resolved'; const a=alerts.find(x=>x.eventId===e.id);if(a)a.status=req.params.action==='resolve'?'resolved':'acknowledged';publish('event:upsert',e);res.json(e)});
io.on('connection',socket=>socket.emit('snapshot',snapshot()));
setInterval(()=>{if(!simulation.running)return;simulation.tick++;for(const bus of buses.filter(b=>b.status==='active')){bus.progress=(bus.progress+.004*simulation.speed)% .999;Object.assign(bus,pointAt(bus),{lastSeen:new Date().toISOString()});} publish('telemetry:update',buses);},Number(process.env.SIMULATION_TICK_MS)||1000);
const port=Number(process.env.PORT)||4000;http.listen(port,()=>console.log(`CityFleet API running at http://localhost:${port}`));
