import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import { MapContainer, TileLayer, Polyline, CircleMarker, Tooltip } from 'react-leaflet';
import { Activity, AlertTriangle, Bus, Camera, CheckCircle2, ChevronRight, CircleDot, Map as MapIcon, Pause, Play, Radio, RotateCcw, ShieldAlert, SlidersHorizontal, Waves, Wrench, X } from 'lucide-react';
import type { Bus as FleetBus, EventType, Snapshot, UrbanEvent } from '@cityfleet/shared';
import 'leaflet/dist/leaflet.css'; import './styles.css';

const api=import.meta.env.VITE_API_URL || 'http://localhost:4000'; const socket=io(api,{autoConnect:false});
const iconFor:Record<EventType,string>={pothole:'◆',congestion:'≋',damaged_sign:'⚑',waterlogging:'≈'}; const titleFor:Record<EventType,string>={pothole:'Road defect',congestion:'Traffic congestion',damaged_sign:'Damaged road sign',waterlogging:'Waterlogging'};
const formatTime=(iso:string)=>new Intl.DateTimeFormat('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(iso));
function App(){
 const [state,setState]=useState<Snapshot|null>(null); const [view,setView]=useState<'command'|'operations'|'analytics'>('command'); const [selected,setSelected]=useState<UrbanEvent|null>(null); const [bus,setBus]=useState<FleetBus|null>(null); const [busy,setBusy]=useState(false);
 useEffect(()=>{ fetch(`${api}/api/snapshot`).then(r=>r.json()).then(setState).catch(()=>undefined); socket.connect(); socket.on('snapshot',setState); return()=>{socket.off('snapshot');socket.disconnect()};},[]);
 useEffect(()=>{if(selected&&state){const next=state.events.find(e=>e.id===selected.id);if(next)setSelected(next)}},[state]);
 const request=async(path:string,body?:unknown)=>{setBusy(true);try{await fetch(`${api}${path}`, {method:'POST',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});}finally{setBusy(false)}};
 if(!state)return <div className="boot"><Radio/> Connecting to CityFleet command network…</div>;
 const active=state.buses.filter(b=>b.status==='active').length, confirmed=state.events.filter(e=>e.status==='confirmed').length, critical=state.events.filter(e=>e.priorityTier==='critical'&&e.status!=='resolved').length;
 return <main><header><div className="brand"><div className="brand-mark"><MapIcon size={19}/></div><div><strong>CityFleet <em>AI</em></strong><span>URBAN INTELLIGENCE COMMAND CENTER</span></div></div><nav>{(['command','operations','analytics'] as const).map(v=><button key={v} onClick={()=>setView(v)} className={view===v?'active':''}>{v==='command'?'Command center':v}</button>)}</nav><div className="header-status"><span><i/>LIVE SIMULATION</span><b>DEMO / SIMULATED DATA</b></div></header>
 <section className="kpis"><Kpi label="Active fleet" value={`${active}/10`} detail="9 reporting telemetry" icon={<Bus/>}/><Kpi label="Active issues" value={String(state.events.filter(e=>e.status!=='resolved').length)} detail={`${confirmed} fleet-confirmed`} icon={<AlertTriangle/>}/><Kpi label="Critical action" value={String(critical)} detail="requires review" icon={<ShieldAlert/>}/><Kpi label="Road condition" value={`${Math.round(state.roads.reduce((a,r)=>a+r.healthScore,0)/state.roads.length)}/100`} detail="network health index" icon={<Activity/>}/></section>
 {view==='command'&&<Command state={state} selected={selected} setSelected={setSelected} bus={bus} setBus={setBus} request={request} busy={busy}/>} {view==='operations'&&<Operations state={state} selected={selected} setSelected={setSelected} request={request}/>} {view==='analytics'&&<Analytics state={state}/>}
 <DemoBar running={state.simulation.running} speed={state.simulation.speed} action={request} busy={busy}/>
 {selected&&<EventDrawer event={selected} road={state.roads.find(r=>r.id===selected.roadId)} close={()=>setSelected(null)} action={request}/>} {bus&&<BusDrawer bus={bus} state={state} close={()=>setBus(null)}/>} 
 </main>
}
function Kpi({label,value,detail,icon}:{label:string;value:string;detail:string;icon:React.ReactNode}){return <article className="kpi"><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>}
function Command({state,selected,setSelected,bus,setBus,request,busy}:{state:Snapshot;selected:UrbanEvent|null;setSelected:(e:UrbanEvent)=>void;bus:FleetBus|null;setBus:(b:FleetBus)=>void;request:(p:string,b?:unknown)=>Promise<void>;busy:boolean}){return <div className="command"><section className="incident-rail"><div className="rail-heading"><div><span>OPERATIONS QUEUE</span><strong>Priority incidents</strong></div><button className="quiet">View all <ChevronRight size={14}/></button></div>{state.events.filter(e=>e.status!=='resolved').sort((a,b)=>b.priority-a.priority).slice(0,6).map(e=><button className={`incident ${selected?.id===e.id?'selected':''}`} key={e.id} onClick={()=>setSelected(e)}><b className={e.priorityTier}/><div><strong>{titleFor[e.type]}</strong><span>{e.roadName} · {e.observationCount} observation{e.observationCount===1?'':'s'}</span></div><mark>{e.priority}</mark></button>)}<div className="road-watch"><span>ROAD HEALTH WATCH</span>{state.roads.sort((a,b)=>a.healthScore-b.healthScore).slice(0,3).map(r=><div key={r.id}><b>{r.name}</b><i><em style={{width:`${r.healthScore}%`}}/></i><strong>{r.healthScore}</strong></div>)}</div></section>
 <section className="map-shell"><div className="map-top"><span><Radio size={14}/> LIVE CITY LAYER</span><div><button className="layer active">Fleet</button><button className="layer">Health</button><button className="layer">Traffic</button></div></div><MapContainer center={[12.9716,77.5946]} zoom={12} className="map" zoomControl={false}><TileLayer attribution="© OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{state.roads.map(r=><Polyline key={r.id} positions={r.geometry.map(p=>[p.lat,p.lng])} pathOptions={{color:r.healthScore<60?'#dc4b4b':r.healthScore<75?'#e7a524':'#46a574',weight:5,opacity:.5}}/>)}{state.buses.filter(b=>b.status==='active').map(b=><CircleMarker key={b.id} center={[b.latitude,b.longitude]} radius={8} pathOptions={{color:'#ecf8ff',weight:2,fillColor:'#1f80c9',fillOpacity:1}} eventHandlers={{click:()=>setBus(b)}}><Tooltip direction="top" offset={[0,-9]}><b>{b.id}</b><br/>{Math.round(b.speed)} km/h</Tooltip></CircleMarker>)}{state.events.filter(e=>e.status!=='resolved').map(e=><CircleMarker key={e.id} center={[e.latitude,e.longitude]} radius={e.priorityTier==='critical'?12:9} pathOptions={{color:'#fff',weight:2,fillColor:e.priorityTier==='critical'?'#d94b4b':e.priorityTier==='high'?'#e6a83e':'#2d8fae',fillOpacity:1}} eventHandlers={{click:()=>setSelected(e)}}><Tooltip direction="top"><b>{iconFor[e.type]} {titleFor[e.type]}</b><br/>{e.status==='confirmed'?'FLEET CONFIRMED':'AWAITING VERIFICATION'}</Tooltip></CircleMarker>)}</MapContainer><div className="map-legend"><span><i className="bus"/>Fleet bus</span><span><i className="critical"/>Critical</span><span><i className="high"/>High</span><span><i className="medium"/>Watch</span></div></section>
 <section className="right-rail"><div className="feed"><span><Camera size={14}/> INFERENCE ACTIVITY</span><div className="camera"><div className="scan"/><div className="box"><b>ROAD SURFACE</b><small>SIMULATED FEED</small></div><p>DemoDetectionProvider · 28ms</p></div><div className="feed-status"><i/><div><b>Edge pipeline available</b><span>Frames are processed on bus; structured events only are sent.</span></div></div></div><div className="recent"><span>RECENT OBSERVATIONS</span>{state.events.slice(0,4).map(e=><button key={e.id} onClick={()=>setSelected(e)}><i className={e.severity}/><div><b>{titleFor[e.type]}</b><small>{formatTime(e.detectedAt)} · {e.observingBusIds.join(', ')}</small></div><strong>{Math.round(e.confidence*100)}%</strong></button>)}</div><Privacy/></section>
 </div>}
function DemoBar({running,speed,action,busy}:{running:boolean;speed:number;action:(p:string,b?:unknown)=>Promise<void>;busy:boolean}){const run=(p:string,b?:unknown)=>action(p,b);return <section className="demo"><div><b><SlidersHorizontal size={16}/> JUDGE DEMO MODE</b><span>Deterministic scenarios drive the full detection → fusion → priority flow.</span></div><div className="sim-controls"><button onClick={()=>run(`/api/simulation/${running?'pause':'start'}`)}>{running?<Pause size={14}/>:<Play size={14}/>} {running?'Pause':'Start'}</button><button onClick={()=>run('/api/simulation/reset')}><RotateCcw size={14}/> Reset</button><label>Speed <select value={speed} onChange={e=>run('/api/simulation/speed',{speed:Number(e.target.value)})}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div><div className="scenarios">{[['pothole','1 · Pothole'],['confirmation','2 · Fleet confirm'],['congestion','3 · Congestion'],['sign','4 · Road sign'],['water','5 · Waterlogging']].map(([id,label])=><button disabled={busy} key={id} onClick={()=>run(`/api/demo/${id}`)}>{label}</button>)}</div></section>}
function EventDrawer({event,road,close,action}:{event:UrbanEvent;road?:Snapshot['roads'][number];close:()=>void;action:(p:string)=>Promise<void>}){return <aside className="drawer"><button className="close" onClick={close}><X/></button><div className="eyebrow"><span className={event.priorityTier}/>{event.status==='confirmed'?'FLEET VERIFIED':'PENDING VERIFICATION'}</div><h2>{titleFor[event.type]}</h2><p>{event.roadName} · {formatTime(event.detectedAt)}</p><div className="evidence"><div className="scan"/><span>SIMULATED CAMERA EVIDENCE</span><b>{event.metadata.provider}</b></div><div className="metric-row"><div><span>Fused confidence</span><strong>{Math.round(event.confidence*100)}%</strong></div><div><span>Road health</span><strong>{road?.healthScore ?? '—'}/100</strong></div><div><span>Priority</span><strong>{event.priority}/100</strong></div></div><h3>Why this was prioritized</h3><ul>{event.priorityReasons.map(x=><li key={x}><CheckCircle2 size={15}/>{x}</li>)}</ul><h3>Observation audit trail</h3><div className="audit">{event.observingBusIds.map((id,i)=><div key={id}><b>{id}</b><span>Observation {i+1} · {event.status==='confirmed'?'contributes to fleet verification':'awaiting corroboration'}</span></div>)}</div><div className="drawer-actions">{event.status!=='resolved'&&<button className="outline" onClick={()=>action(`/api/events/${event.id}/acknowledge`)}>Acknowledge</button>}<button className="danger" onClick={()=>action(`/api/events/${event.id}/resolve`)}>Mark resolved</button></div></aside>}
function BusDrawer({bus,state,close}:{bus:FleetBus;state:Snapshot;close:()=>void}){const route=state.routes.find(r=>r.id===bus.routeId)!;const history=state.events.filter(e=>e.observingBusIds.includes(bus.id));return <aside className="drawer bus-drawer"><button className="close" onClick={close}><X/></button><div className="eyebrow"><span className="medium"/> LIVE VEHICLE</div><h2>{bus.id}</h2><p>{bus.registrationNumber} · Route {route.number}</p><div className="camera bus-camera"><div className="scan"/><span>FORWARD CAMERA / SIMULATED</span></div><div className="telemetry"><div><span>Speed</span><b>{Math.round(bus.speed)} km/h</b></div><div><span>Heading</span><b>{Math.round(bus.heading)}°</b></div><div><span>Status</span><b>Active</b></div></div><h3>Recent detections</h3>{history.length?history.map(e=><div className="audit" key={e.id}><div><b>{titleFor[e.type]}</b><span>{e.roadName} · {Math.round(e.confidence*100)}% confidence</span></div></div>):<p className="empty">No detections reported during this session.</p>}</aside>}
function Operations({state,selected,setSelected,request}:{state:Snapshot;selected:UrbanEvent|null;setSelected:(e:UrbanEvent|null)=>void;request:(p:string)=>Promise<void>}){return <section className="page-grid"><div className="page-title"><div><span>LIVE WORK QUEUE</span><h1>Alerts & authority actions</h1><p>Priorities are explainable: severity, fused confidence, repeated observations, traffic exposure and recency.</p></div><button className="export">Export work queue</button></div><div className="table-card"><div className="table-head"><span>Priority</span><span>Issue</span><span>Verification</span><span>Affected road</span><span>Action</span></div>{state.events.filter(e=>e.status!=='resolved').sort((a,b)=>b.priority-a.priority).map(e=><div className="table-row" key={e.id}><span><b className={`pill ${e.priorityTier}`}>{e.priorityTier}</b><small>{e.priority}/100</small></span><span><strong>{titleFor[e.type]}</strong><small>{formatTime(e.detectedAt)}</small></span><span><b>{e.observationCount} bus{e.observationCount===1?'':'es'}</b><small>{Math.round(e.confidence*100)}% confidence</small></span><span>{e.roadName}<small>Health: {state.roads.find(r=>r.id===e.roadId)?.healthScore}/100</small></span><span><button className="open" onClick={()=>setSelected(e)}>Inspect</button><button className="resolve" onClick={()=>request(`/api/events/${e.id}/resolve`)}>Resolve</button></span></div>)}</div>{selected&&<EventDrawer event={selected} road={state.roads.find(r=>r.id===selected.roadId)} close={()=>setSelected(null)} action={request}/>}</section>}
function Analytics({state}:{state:Snapshot}){const types=Object.entries(state.events.reduce((a,e)=>{a[e.type]=(a[e.type]||0)+1;return a},{} as Record<string,number>)).map(([name,value])=>({name:name.replace('_',' '),value}));const health=state.roads.map(r=>({name:r.name.replace(' Road',''),score:r.healthScore}));const max=Math.max(1,...types.map(x=>x.value));const history=state.roads[0].history;return <section className="page-grid"><div className="page-title"><div><span>SIMULATED DATASET</span><h1>Network intelligence</h1><p>Historical seed observations plus activity produced in this local session.</p></div></div><div className="analytics"><article><h3>Events by type</h3><div className="bar-chart">{types.map(x=><div key={x.name}><i style={{height:`${(x.value/max)*170}px`}}/><b>{x.value}</b><span>{x.name}</span></div>)}</div></article><article><h3>Road health score</h3><div className="health-chart">{health.map(x=><div key={x.name}><span>{x.name}</span><i><b style={{width:`${x.score}%`}}/></i><strong>{x.score}</strong></div>)}</div></article><article className="wide"><h3>Network health history</h3><div className="history-chart">{history.map((x,i)=><div key={x.at} title={`${x.score}/100`} style={{height:`${x.score}%`}}><span>{i===history.length-1?x.score:''}</span></div>)}</div><small className="chart-note">MG Road health score — recorded after each relevant event update.</small></article></div></section>}
function Privacy(){return <p className="privacy"><ShieldAlert size={13}/><b>Privacy note</b> This demo transmits synthetic, structured detections only. A production deployment needs retention controls, access management and lawful privacy governance.</p>}
createRoot(document.getElementById('root')!).render(<App/>);
